package com.explitech.fiata.dao;

import com.explitech.fiata.model.Comment;
import com.explitech.fiata.model.CommentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CommentMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment
	 * @mbggenerated  Tue May 26 21:06:30 CST 2015
	 */
	int countByExample(CommentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment
	 * @mbggenerated  Tue May 26 21:06:30 CST 2015
	 */
	int deleteByExample(CommentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment
	 * @mbggenerated  Tue May 26 21:06:30 CST 2015
	 */
	int deleteByPrimaryKey(Integer commentId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment
	 * @mbggenerated  Tue May 26 21:06:30 CST 2015
	 */
	int insert(Comment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment
	 * @mbggenerated  Tue May 26 21:06:30 CST 2015
	 */
	int insertSelective(Comment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment
	 * @mbggenerated  Tue May 26 21:06:30 CST 2015
	 */
	List<Comment> selectByExampleWithBLOBs(CommentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment
	 * @mbggenerated  Tue May 26 21:06:30 CST 2015
	 */
	List<Comment> selectByExample(CommentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment
	 * @mbggenerated  Tue May 26 21:06:30 CST 2015
	 */
	Comment selectByPrimaryKey(Integer commentId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment
	 * @mbggenerated  Tue May 26 21:06:30 CST 2015
	 */
	int updateByExampleSelective(@Param("record") Comment record,
			@Param("example") CommentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment
	 * @mbggenerated  Tue May 26 21:06:30 CST 2015
	 */
	int updateByExampleWithBLOBs(@Param("record") Comment record,
			@Param("example") CommentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment
	 * @mbggenerated  Tue May 26 21:06:30 CST 2015
	 */
	int updateByExample(@Param("record") Comment record,
			@Param("example") CommentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment
	 * @mbggenerated  Tue May 26 21:06:30 CST 2015
	 */
	int updateByPrimaryKeySelective(Comment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment
	 * @mbggenerated  Tue May 26 21:06:30 CST 2015
	 */
	int updateByPrimaryKeyWithBLOBs(Comment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment
	 * @mbggenerated  Tue May 26 21:06:30 CST 2015
	 */
	int updateByPrimaryKey(Comment record);
}