package com.explitech.fiata.dao;

import com.explitech.fiata.model.Company;
import com.explitech.fiata.model.CompanyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CompanyMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table company
	 * @mbggenerated  Tue May 26 21:06:30 CST 2015
	 */
	int countByExample(CompanyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table company
	 * @mbggenerated  Tue May 26 21:06:30 CST 2015
	 */
	int deleteByExample(CompanyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table company
	 * @mbggenerated  Tue May 26 21:06:30 CST 2015
	 */
	int deleteByPrimaryKey(Integer companyId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table company
	 * @mbggenerated  Tue May 26 21:06:30 CST 2015
	 */
	int insert(Company record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table company
	 * @mbggenerated  Tue May 26 21:06:30 CST 2015
	 */
	int insertSelective(Company record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table company
	 * @mbggenerated  Tue May 26 21:06:30 CST 2015
	 */
	List<Company> selectByExampleWithBLOBs(CompanyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table company
	 * @mbggenerated  Tue May 26 21:06:30 CST 2015
	 */
	List<Company> selectByExample(CompanyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table company
	 * @mbggenerated  Tue May 26 21:06:30 CST 2015
	 */
	Company selectByPrimaryKey(Integer companyId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table company
	 * @mbggenerated  Tue May 26 21:06:30 CST 2015
	 */
	int updateByExampleSelective(@Param("record") Company record,
			@Param("example") CompanyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table company
	 * @mbggenerated  Tue May 26 21:06:30 CST 2015
	 */
	int updateByExampleWithBLOBs(@Param("record") Company record,
			@Param("example") CompanyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table company
	 * @mbggenerated  Tue May 26 21:06:30 CST 2015
	 */
	int updateByExample(@Param("record") Company record,
			@Param("example") CompanyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table company
	 * @mbggenerated  Tue May 26 21:06:30 CST 2015
	 */
	int updateByPrimaryKeySelective(Company record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table company
	 * @mbggenerated  Tue May 26 21:06:30 CST 2015
	 */
	int updateByPrimaryKeyWithBLOBs(Company record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table company
	 * @mbggenerated  Tue May 26 21:06:30 CST 2015
	 */
	int updateByPrimaryKey(Company record);
}