package com.explitech.fiata.model;

import java.io.Serializable;
import java.util.Date;

import org.codehaus.jackson.map.annotate.JsonView;

import com.explitech.fiata.common.ServiceObjectView;


public class Comment implements Serializable{
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comment.comment_id
	 * @mbggenerated  Tue May 26 21:06:30 CST 2015
	 */
	@JsonView(ServiceObjectView.CommentView.class)
	private Integer commentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comment.user_id
	 * @mbggenerated  Tue May 26 21:06:30 CST 2015
	 */
	@JsonView(ServiceObjectView.CommentView.class)
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comment.comment_date
	 * @mbggenerated  Tue May 26 21:06:30 CST 2015
	 */
	@JsonView(ServiceObjectView.CommentView.class)
	private Date commentDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comment.content
	 * @mbggenerated  Tue May 26 21:06:30 CST 2015
	 */
	@JsonView(ServiceObjectView.CommentView.class)
	private String content;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comment.comment_id
	 * @return  the value of comment.comment_id
	 * @mbggenerated  Tue May 26 21:06:30 CST 2015
	 */
	@JsonView(ServiceObjectView.CommentView.class)
	public Integer getCommentId() {
		return commentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comment.comment_id
	 * @param commentId  the value for comment.comment_id
	 * @mbggenerated  Tue May 26 21:06:30 CST 2015
	 */
	public void setCommentId(Integer commentId) {
		this.commentId = commentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comment.user_id
	 * @return  the value of comment.user_id
	 * @mbggenerated  Tue May 26 21:06:30 CST 2015
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comment.user_id
	 * @param userId  the value for comment.user_id
	 * @mbggenerated  Tue May 26 21:06:30 CST 2015
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comment.comment_date
	 * @return  the value of comment.comment_date
	 * @mbggenerated  Tue May 26 21:06:30 CST 2015
	 */
	public Date getCommentDate() {
		return commentDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comment.comment_date
	 * @param commentDate  the value for comment.comment_date
	 * @mbggenerated  Tue May 26 21:06:30 CST 2015
	 */
	public void setCommentDate(Date commentDate) {
		this.commentDate = commentDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comment.content
	 * @return  the value of comment.content
	 * @mbggenerated  Tue May 26 21:06:30 CST 2015
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comment.content
	 * @param content  the value for comment.content
	 * @mbggenerated  Tue May 26 21:06:30 CST 2015
	 */
	public void setContent(String content) {
		this.content = content;
	}

	/**
	 * 
	 */
	private static final long serialVersionUID = -2917210949578932535L;
}