package com.explitech.fiata.model;

import java.util.Date;

public class Ticket {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.ticket_id
     *
     * @mbggenerated Tue May 26 21:06:30 CST 2015
     */
    private Integer ticketId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.topic
     *
     * @mbggenerated Tue May 26 21:06:30 CST 2015
     */
    private String topic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.user_id
     *
     * @mbggenerated Tue May 26 21:06:30 CST 2015
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.ticket_date
     *
     * @mbggenerated Tue May 26 21:06:30 CST 2015
     */
    private Date ticketDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.content
     *
     * @mbggenerated Tue May 26 21:06:30 CST 2015
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.ticket_id
     *
     * @return the value of ticket.ticket_id
     *
     * @mbggenerated Tue May 26 21:06:30 CST 2015
     */
    public Integer getTicketId() {
        return ticketId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.ticket_id
     *
     * @param ticketId the value for ticket.ticket_id
     *
     * @mbggenerated Tue May 26 21:06:30 CST 2015
     */
    public void setTicketId(Integer ticketId) {
        this.ticketId = ticketId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.topic
     *
     * @return the value of ticket.topic
     *
     * @mbggenerated Tue May 26 21:06:30 CST 2015
     */
    public String getTopic() {
        return topic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.topic
     *
     * @param topic the value for ticket.topic
     *
     * @mbggenerated Tue May 26 21:06:30 CST 2015
     */
    public void setTopic(String topic) {
        this.topic = topic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.user_id
     *
     * @return the value of ticket.user_id
     *
     * @mbggenerated Tue May 26 21:06:30 CST 2015
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.user_id
     *
     * @param userId the value for ticket.user_id
     *
     * @mbggenerated Tue May 26 21:06:30 CST 2015
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.ticket_date
     *
     * @return the value of ticket.ticket_date
     *
     * @mbggenerated Tue May 26 21:06:30 CST 2015
     */
    public Date getTicketDate() {
        return ticketDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.ticket_date
     *
     * @param ticketDate the value for ticket.ticket_date
     *
     * @mbggenerated Tue May 26 21:06:30 CST 2015
     */
    public void setTicketDate(Date ticketDate) {
        this.ticketDate = ticketDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.content
     *
     * @return the value of ticket.content
     *
     * @mbggenerated Tue May 26 21:06:30 CST 2015
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.content
     *
     * @param content the value for ticket.content
     *
     * @mbggenerated Tue May 26 21:06:30 CST 2015
     */
    public void setContent(String content) {
        this.content = content;
    }
}