package com.explitech.fiata.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table user
	 * @mbggenerated  Tue May 26 21:06:30 CST 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table user
	 * @mbggenerated  Tue May 26 21:06:30 CST 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table user
	 * @mbggenerated  Tue May 26 21:06:30 CST 2015
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Tue May 26 21:06:30 CST 2015
	 */
	public UserExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Tue May 26 21:06:30 CST 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Tue May 26 21:06:30 CST 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Tue May 26 21:06:30 CST 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Tue May 26 21:06:30 CST 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Tue May 26 21:06:30 CST 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Tue May 26 21:06:30 CST 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Tue May 26 21:06:30 CST 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Tue May 26 21:06:30 CST 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Tue May 26 21:06:30 CST 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Tue May 26 21:06:30 CST 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table user
	 * @mbggenerated  Tue May 26 21:06:30 CST 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andUserIdIsNull() {
			addCriterion("user_id is null");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNotNull() {
			addCriterion("user_id is not null");
			return (Criteria) this;
		}

		public Criteria andUserIdEqualTo(Integer value) {
			addCriterion("user_id =", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotEqualTo(Integer value) {
			addCriterion("user_id <>", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThan(Integer value) {
			addCriterion("user_id >", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("user_id >=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThan(Integer value) {
			addCriterion("user_id <", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThanOrEqualTo(Integer value) {
			addCriterion("user_id <=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdIn(List<Integer> values) {
			addCriterion("user_id in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotIn(List<Integer> values) {
			addCriterion("user_id not in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdBetween(Integer value1, Integer value2) {
			addCriterion("user_id between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
			addCriterion("user_id not between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andNicknameIsNull() {
			addCriterion("nickname is null");
			return (Criteria) this;
		}

		public Criteria andNicknameIsNotNull() {
			addCriterion("nickname is not null");
			return (Criteria) this;
		}

		public Criteria andNicknameEqualTo(String value) {
			addCriterion("nickname =", value, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameNotEqualTo(String value) {
			addCriterion("nickname <>", value, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameGreaterThan(String value) {
			addCriterion("nickname >", value, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameGreaterThanOrEqualTo(String value) {
			addCriterion("nickname >=", value, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameLessThan(String value) {
			addCriterion("nickname <", value, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameLessThanOrEqualTo(String value) {
			addCriterion("nickname <=", value, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameLike(String value) {
			addCriterion("nickname like", value, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameNotLike(String value) {
			addCriterion("nickname not like", value, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameIn(List<String> values) {
			addCriterion("nickname in", values, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameNotIn(List<String> values) {
			addCriterion("nickname not in", values, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameBetween(String value1, String value2) {
			addCriterion("nickname between", value1, value2, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameNotBetween(String value1, String value2) {
			addCriterion("nickname not between", value1, value2, "nickname");
			return (Criteria) this;
		}

		public Criteria andCellphoneIsNull() {
			addCriterion("cellphone is null");
			return (Criteria) this;
		}

		public Criteria andCellphoneIsNotNull() {
			addCriterion("cellphone is not null");
			return (Criteria) this;
		}

		public Criteria andCellphoneEqualTo(String value) {
			addCriterion("cellphone =", value, "cellphone");
			return (Criteria) this;
		}

		public Criteria andCellphoneNotEqualTo(String value) {
			addCriterion("cellphone <>", value, "cellphone");
			return (Criteria) this;
		}

		public Criteria andCellphoneGreaterThan(String value) {
			addCriterion("cellphone >", value, "cellphone");
			return (Criteria) this;
		}

		public Criteria andCellphoneGreaterThanOrEqualTo(String value) {
			addCriterion("cellphone >=", value, "cellphone");
			return (Criteria) this;
		}

		public Criteria andCellphoneLessThan(String value) {
			addCriterion("cellphone <", value, "cellphone");
			return (Criteria) this;
		}

		public Criteria andCellphoneLessThanOrEqualTo(String value) {
			addCriterion("cellphone <=", value, "cellphone");
			return (Criteria) this;
		}

		public Criteria andCellphoneLike(String value) {
			addCriterion("cellphone like", value, "cellphone");
			return (Criteria) this;
		}

		public Criteria andCellphoneNotLike(String value) {
			addCriterion("cellphone not like", value, "cellphone");
			return (Criteria) this;
		}

		public Criteria andCellphoneIn(List<String> values) {
			addCriterion("cellphone in", values, "cellphone");
			return (Criteria) this;
		}

		public Criteria andCellphoneNotIn(List<String> values) {
			addCriterion("cellphone not in", values, "cellphone");
			return (Criteria) this;
		}

		public Criteria andCellphoneBetween(String value1, String value2) {
			addCriterion("cellphone between", value1, value2, "cellphone");
			return (Criteria) this;
		}

		public Criteria andCellphoneNotBetween(String value1, String value2) {
			addCriterion("cellphone not between", value1, value2, "cellphone");
			return (Criteria) this;
		}

		public Criteria andHashIsNull() {
			addCriterion("hash is null");
			return (Criteria) this;
		}

		public Criteria andHashIsNotNull() {
			addCriterion("hash is not null");
			return (Criteria) this;
		}

		public Criteria andHashEqualTo(String value) {
			addCriterion("hash =", value, "hash");
			return (Criteria) this;
		}

		public Criteria andHashNotEqualTo(String value) {
			addCriterion("hash <>", value, "hash");
			return (Criteria) this;
		}

		public Criteria andHashGreaterThan(String value) {
			addCriterion("hash >", value, "hash");
			return (Criteria) this;
		}

		public Criteria andHashGreaterThanOrEqualTo(String value) {
			addCriterion("hash >=", value, "hash");
			return (Criteria) this;
		}

		public Criteria andHashLessThan(String value) {
			addCriterion("hash <", value, "hash");
			return (Criteria) this;
		}

		public Criteria andHashLessThanOrEqualTo(String value) {
			addCriterion("hash <=", value, "hash");
			return (Criteria) this;
		}

		public Criteria andHashLike(String value) {
			addCriterion("hash like", value, "hash");
			return (Criteria) this;
		}

		public Criteria andHashNotLike(String value) {
			addCriterion("hash not like", value, "hash");
			return (Criteria) this;
		}

		public Criteria andHashIn(List<String> values) {
			addCriterion("hash in", values, "hash");
			return (Criteria) this;
		}

		public Criteria andHashNotIn(List<String> values) {
			addCriterion("hash not in", values, "hash");
			return (Criteria) this;
		}

		public Criteria andHashBetween(String value1, String value2) {
			addCriterion("hash between", value1, value2, "hash");
			return (Criteria) this;
		}

		public Criteria andHashNotBetween(String value1, String value2) {
			addCriterion("hash not between", value1, value2, "hash");
			return (Criteria) this;
		}

		public Criteria andUserTypeIdIsNull() {
			addCriterion("user_type_id is null");
			return (Criteria) this;
		}

		public Criteria andUserTypeIdIsNotNull() {
			addCriterion("user_type_id is not null");
			return (Criteria) this;
		}

		public Criteria andUserTypeIdEqualTo(Integer value) {
			addCriterion("user_type_id =", value, "userTypeId");
			return (Criteria) this;
		}

		public Criteria andUserTypeIdNotEqualTo(Integer value) {
			addCriterion("user_type_id <>", value, "userTypeId");
			return (Criteria) this;
		}

		public Criteria andUserTypeIdGreaterThan(Integer value) {
			addCriterion("user_type_id >", value, "userTypeId");
			return (Criteria) this;
		}

		public Criteria andUserTypeIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("user_type_id >=", value, "userTypeId");
			return (Criteria) this;
		}

		public Criteria andUserTypeIdLessThan(Integer value) {
			addCriterion("user_type_id <", value, "userTypeId");
			return (Criteria) this;
		}

		public Criteria andUserTypeIdLessThanOrEqualTo(Integer value) {
			addCriterion("user_type_id <=", value, "userTypeId");
			return (Criteria) this;
		}

		public Criteria andUserTypeIdIn(List<Integer> values) {
			addCriterion("user_type_id in", values, "userTypeId");
			return (Criteria) this;
		}

		public Criteria andUserTypeIdNotIn(List<Integer> values) {
			addCriterion("user_type_id not in", values, "userTypeId");
			return (Criteria) this;
		}

		public Criteria andUserTypeIdBetween(Integer value1, Integer value2) {
			addCriterion("user_type_id between", value1, value2, "userTypeId");
			return (Criteria) this;
		}

		public Criteria andUserTypeIdNotBetween(Integer value1, Integer value2) {
			addCriterion("user_type_id not between", value1, value2,
					"userTypeId");
			return (Criteria) this;
		}

		public Criteria andCompanyIdIsNull() {
			addCriterion("company_id is null");
			return (Criteria) this;
		}

		public Criteria andCompanyIdIsNotNull() {
			addCriterion("company_id is not null");
			return (Criteria) this;
		}

		public Criteria andCompanyIdEqualTo(Integer value) {
			addCriterion("company_id =", value, "companyId");
			return (Criteria) this;
		}

		public Criteria andCompanyIdNotEqualTo(Integer value) {
			addCriterion("company_id <>", value, "companyId");
			return (Criteria) this;
		}

		public Criteria andCompanyIdGreaterThan(Integer value) {
			addCriterion("company_id >", value, "companyId");
			return (Criteria) this;
		}

		public Criteria andCompanyIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("company_id >=", value, "companyId");
			return (Criteria) this;
		}

		public Criteria andCompanyIdLessThan(Integer value) {
			addCriterion("company_id <", value, "companyId");
			return (Criteria) this;
		}

		public Criteria andCompanyIdLessThanOrEqualTo(Integer value) {
			addCriterion("company_id <=", value, "companyId");
			return (Criteria) this;
		}

		public Criteria andCompanyIdIn(List<Integer> values) {
			addCriterion("company_id in", values, "companyId");
			return (Criteria) this;
		}

		public Criteria andCompanyIdNotIn(List<Integer> values) {
			addCriterion("company_id not in", values, "companyId");
			return (Criteria) this;
		}

		public Criteria andCompanyIdBetween(Integer value1, Integer value2) {
			addCriterion("company_id between", value1, value2, "companyId");
			return (Criteria) this;
		}

		public Criteria andCompanyIdNotBetween(Integer value1, Integer value2) {
			addCriterion("company_id not between", value1, value2, "companyId");
			return (Criteria) this;
		}

		public Criteria andDateAddIsNull() {
			addCriterion("date_add is null");
			return (Criteria) this;
		}

		public Criteria andDateAddIsNotNull() {
			addCriterion("date_add is not null");
			return (Criteria) this;
		}

		public Criteria andDateAddEqualTo(Date value) {
			addCriterion("date_add =", value, "dateAdd");
			return (Criteria) this;
		}

		public Criteria andDateAddNotEqualTo(Date value) {
			addCriterion("date_add <>", value, "dateAdd");
			return (Criteria) this;
		}

		public Criteria andDateAddGreaterThan(Date value) {
			addCriterion("date_add >", value, "dateAdd");
			return (Criteria) this;
		}

		public Criteria andDateAddGreaterThanOrEqualTo(Date value) {
			addCriterion("date_add >=", value, "dateAdd");
			return (Criteria) this;
		}

		public Criteria andDateAddLessThan(Date value) {
			addCriterion("date_add <", value, "dateAdd");
			return (Criteria) this;
		}

		public Criteria andDateAddLessThanOrEqualTo(Date value) {
			addCriterion("date_add <=", value, "dateAdd");
			return (Criteria) this;
		}

		public Criteria andDateAddIn(List<Date> values) {
			addCriterion("date_add in", values, "dateAdd");
			return (Criteria) this;
		}

		public Criteria andDateAddNotIn(List<Date> values) {
			addCriterion("date_add not in", values, "dateAdd");
			return (Criteria) this;
		}

		public Criteria andDateAddBetween(Date value1, Date value2) {
			addCriterion("date_add between", value1, value2, "dateAdd");
			return (Criteria) this;
		}

		public Criteria andDateAddNotBetween(Date value1, Date value2) {
			addCriterion("date_add not between", value1, value2, "dateAdd");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table user
	 * @mbggenerated  Tue May 26 21:06:30 CST 2015
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user
     *
     * @mbggenerated do_not_delete_during_merge Fri May 08 23:00:53 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}