package com.explitech.fiata.model;

import java.io.Serializable;

import org.codehaus.jackson.map.annotate.JsonView;

import com.explitech.fiata.common.ServiceObjectView;


public class UserType implements Serializable {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_type.user_type_id
	 * @mbggenerated  Tue May 26 21:06:30 CST 2015
	 */
	@JsonView(ServiceObjectView.UserTypeView.class)
	private Integer userTypeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_type.user_type_name
	 * @mbggenerated  Tue May 26 21:06:30 CST 2015
	 */
	@JsonView(ServiceObjectView.UserTypeView.class)
	private String userTypeName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_type.sort
	 * @mbggenerated  Tue May 26 21:06:30 CST 2015
	 */
	@JsonView(ServiceObjectView.UserTypeView.class)
	private Integer sort;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_type.user_type_id
	 * @return  the value of user_type.user_type_id
	 * @mbggenerated  Tue May 26 21:06:30 CST 2015
	 */
	public Integer getUserTypeId() {
		return userTypeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_type.user_type_id
	 * @param userTypeId  the value for user_type.user_type_id
	 * @mbggenerated  Tue May 26 21:06:30 CST 2015
	 */
	public void setUserTypeId(Integer userTypeId) {
		this.userTypeId = userTypeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_type.user_type_name
	 * @return  the value of user_type.user_type_name
	 * @mbggenerated  Tue May 26 21:06:30 CST 2015
	 */
	public String getUserTypeName() {
		return userTypeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_type.user_type_name
	 * @param userTypeName  the value for user_type.user_type_name
	 * @mbggenerated  Tue May 26 21:06:30 CST 2015
	 */
	public void setUserTypeName(String userTypeName) {
		this.userTypeName = userTypeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_type.sort
	 * @return  the value of user_type.sort
	 * @mbggenerated  Tue May 26 21:06:30 CST 2015
	 */
	public Integer getSort() {
		return sort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_type.sort
	 * @param sort  the value for user_type.sort
	 * @mbggenerated  Tue May 26 21:06:30 CST 2015
	 */
	public void setSort(Integer sort) {
		this.sort = sort;
	}

	/**
	 * 
	 */
	private static final long serialVersionUID = 1664892270740098325L;
}